name: julia
channels:
  - conda-forge
dependencies:
# r dependencies
  - r-base
  - r-tidyverse
  - r-randomForest
  - r-ggplot2
  - r-caret
  - r-xgboost
  - r-e1071
  - r-iml
  - r-rcolorbrewer
  - r-reshape2
  - r-gridextra
  - r-rstatix
  - r-ggpubr
  - r-plyr
# python dependencies
  - python
  - numpy
  - pip
  - pandas
  - matplotlib
  - scikit-learn
