name: julia
channels:
  - conda-forge
dependencies:
# r dependencies
  - r-base=4.1
  - r-tidyverse
  - r-randomForest
  - r-ggplot2
  - r-caret
  - r-xgboost
# python dependencies
  - python
  - numpy
  - pip
  - pandas
  - matplotlib
  - sklearn
